name: Test PHPUnit

on:
  workflow_dispatch:
  pull_request:
  # Once daily at 00:00 UTC.
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ 'pull_request' == github.event_name && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:

  # Dynamically builds the "include" var for the matrix on the "test" job
  #
  # This is constructed dynamically in order to allow us to share a single phpunit config for all add-ons
  # but only includes the job for add-on repos.
  set-matrix-include:
    name: Set main job matrix "include" var
    runs-on: ubuntu-latest
    outputs:
      include: ${{ steps.set-output.outputs.include }}
    steps:
      - name: Set Output
        id: set-output
        run: |
          INCLUDE='[
            {
              "PHP": "8.0",
              "WP": "nightly",
              "allow-failure": true
            },
            {
              "PHP": "8.1",
              "WP": "nightly",
              "allow-failure": true
            },
            {
              "name-append": " (LLMS nightly)",
              "PHP": "8.0",
              "WP": "5.8",
              "LLMS": "dev",
              "allow-failure": true
            }
          ]' | jq -rcM
          if [[ "gocodebox/lifterlms" == ${{ github.repository }} ]]; then
            INCLUDE=$( echo $INCLUDE | jq -rcM 'del(.[2])' )
          fi
          echo $INCLUDE
          echo "::set-output name=include::$INCLUDE"

  test:
    name: WP ${{ matrix.WP }} on PHP ${{ matrix.PHP }}${{ matrix.name-append }}

    needs: set-matrix-include
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}

    strategy:
      fail-fast: false
      matrix:
        WP:
          - '5.8'
          - '5.7'
          - '5.6'
          - '5.5'
          - '5.4'
        PHP:
          - '8.0'
          - '7.4'
          - '7.3'
        LLMS:
          - false
        allow-failure:
          - false
        name-append:
          - ''

        include: ${{ fromJSON( needs.set-matrix-include.outputs.include ) }}

        exclude:
          # These WP Versions don't work on PHP 8.0
          - PHP: '8.0'
            WP: '5.5'
          - PHP: '8.0'
            WP: '5.4'

    steps:

      - name: Setup Environment
        uses: gocodebox/.github/.github/actions/setup-phpunit@trunk
        with:
          php-version: ${{ matrix.PHP }}
          wp-version: ${{ matrix.WP }}
          llms-branch: ${{ matrix.LLMS }}

      # Run Tests.
      - name: Run Tests
        run: composer run tests

