name: 'Organization Team Settings'
description: 'Manages team repository permissions'
inputs:
  repo-token:
    description: 'A GitHub access token secret - must have the admin:org scope'
runs:
  using: 'node12'
  main: 'index.js'