name: 'Organization Team Settings'
description: 'Manages teams, team members, and team repository access'
inputs:
  repo-token:
    description: 'A GitHub access token secret - must have the admin:org scope'
runs:
  using: 'node12'
  main: 'dist/index.js'