name: New Issue Triage and Assignment

on:
  issues:
    types: [ opened ]

jobs:
  handle-new-issue:
    runs-on: ubuntu-latest
    env:
      PRIMARY_CODEOWNER: '@thomasplevy'
    steps:
      - name: Add to "Triage" project
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Triage
          column: Awaiting Triage
          repo-token: ${{ secrets.ORG_WORKFLOWS }}

      - name: Parse CODEOWNERS file
        id: codeowner
        if: hashFiles( '.github/CODEOWNERS' ) != ''
        uses: SvanBoxel/codeowners-action@v1
      
      - name: Use Primary CODEOWNER from file
        if: hashFiles( '.github/CODEOWNERS' ) != ''
        run: |
          echo "PRIMARY_CODEOWNER=${{ steps.codeowners.outputs.codeowners['*'] }}" >> $GITHUB_ENV

      - name: Strip @ from username
        run: |
          echo "PRIMARY_CODEOWNER=${PRIMARY_CODEOWNER#?}" >> $GITHUB_ENV
          echo "Assigning issue to ${{ env.PRIMARY_CODEOWNER }}

      - name: Assign issue
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.ORG_WORKFLOWS }}
          assignees: ${{ env.PRIMARY_CODEOWNER }}