name: Sync Organization Files

on:
  push:
    paths:
      # PHP Files.
      - .github/workflow-templates/coding-standards.yml
      - .github/workflow-templates/php-test-coverage.yml
      - .github/workflow-templates/test-phpunit.yml

      # Utils.
      - .github/workflows/issue-triage.yml
      - .github/workflows/pr-ready.yml

      # When this file is edited.
      - .github/workflows/workflow-sync.yml
    branches:
      - trunk
    workflow_dispatch:

env:
  DRY_RUN: false

  PHP_FILES: |
    .github/workflow-templates/coding-standards.yml=.github/workflows/coding-standards.yml
    .github/workflow-templates/php-test-coverage.yml=.github/workflows/php-test-coverage.yml
    .github/workflow-templates/test-phpunit.yml=.github/workflows/test-phpunit.yml
  PHP_REPOS: |
    gocodebox/lifterlms
    gocodebox/lifterlms-advanced-quizzes

  # Utility workflows.
  UTIL_FILES: |
    .github/workflows/issue-triage.yml
    .github/workflows/pr-ready.yml
  UTIL_REPOS: |
    gocodebox/lifterlms
    gocodebox/lifterlms-advanced-quizzes
    gocodebox/lifterlms-advanced-videos
    gocodebox/lifterlms-assignments
    gocodebox/lifterlms-blocks
    gocodebox/lifterlms-convertkit
    gocodebox/lifterlms-cli
    gocodebox/lifterlms-custom-fields
    gocodebox/lifterlms-gateway-authorize-net
    gocodebox/lifterlms-gateway-paypal
    gocodebox/lifterlms-groups
    gocodebox/lifterlms-helper
    gocodebox/lifterlms-integration-formidable-forms
    gocodebox/lifterlms-integration-gravity-forms
    gocodebox/lifterlms-integration-ninja-forms
    gocodebox/lifterlms-integration-twilio
    gocodebox/lifterlms-integration-woocommerce
    gocodebox/lifterlms-integration-wpforms
    gocodebox/lifterlms-labs
    gocodebox/lifterlms-lite-lms-progress-tracker
    gocodebox/lifterlms-mailchimp
    gocodebox/lifterlms-pdfs
    gocodebox/lifterlms-private-areas
    gocodebox/lifterlms-rest
    gocodebox/lifterlms-social-learning
    gocodebox/lifterlms-stripe
    gocodebox/lifterlms-virtual-classrooms
    gocodebox/lifterlms-launchpad
    gocodebox/lifterlms-launchpad-child
    gocodebox/sky-pilot
    gocodebox/lifterlms-zapier
    gocodebox/lifterlms-api-node
    gocodebox/private-issues
    gocodebox/snippets
    gocodebox/dev-tools
    gocodebox/lifterlms-brand
    gocodebox/lifterlms-lib-tasks
    gocodebox/lifterlms-cs
    gocodebox/lifterlms-tests
    gocodebox/llms-releaser
    gocodebox/lifterlms.com
    gocodebox/myliftersite.com
    gocodebox/developer.lifterlms.com
    gocodebox/telemetry.lifterlms.com
    gocodebox/llms-academy-rest
    gocodebox/lifterlms-com-reporting
    gocodebox/lifterlms-com-experiments
    gocodebox/lifterlms.com-rest-api
    gocodebox/lifterlms-com-support-desk

jobs:

  php-workflows:
    name: PHP Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync workflow files
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.PHP_REPOS }}
          WORKFLOW_FILES: ${{ env.PHP_FILES }}
          GITHUB_TOKEN: ${{ secrets.ORG_WORKFLOWS }}
          COMMIT_MESSAGE: "PHP Workflow File Sync [Runner ID: $GITHUB_RUN_NUMBER]"

  util-files:
    name: Utility Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync workflow files
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.UTIL_REPOS }}
          WORKFLOW_FILES: ${{ env.UTIL_FILES }}
          GITHUB_TOKEN: ${{ secrets.ORG_WORKFLOWS }}
          COMMIT_MESSAGE: "Utility File Sync [Runner ID: $GITHUB_RUN_NUMBER]"